env: "local"
storage_path: "./storage.db"
github_secret: ""
http_server:
  address: "localhost:8080"
  timeout: 4s
  iddle_timeout: 60s
  shutdown_timeout: 10s
kafka:
  topic: "ai_assistant_tasks"
  server_address: "localhost:9092"
  consumer_topic: "ai_assistant_responses"
  consumer_group: "ai_assistant_responses_group"
background:
  send_worker_timeout: 10s