env: "local"
storage_path: "./storage.db"
github_secret: "pidor"
tg_secret: "7194043216:AAE91RDTVrVVzUBm23_Jh49AUbNU9YOj2n8"
http_requests_max: 20
http_server:
  address: ":8082"
  timeout: 4s
  iddle_timeout: 60s
  shutdown_timeout: 10s
kafka:
  topic: "ai_assistant_tasks"
  server_address: "kafka:9092"
  consumer_topic: "ai_assistant_responses"
  consumer_group: "ai_assistant_responses_group"
background:
  send_worker_timeout: 30s
